version: 2

jobs:
  build:
    docker:
      - image: alpine
    steps:
      - checkout
      - run:
          name: Echo Test
          command: echo "CircleCI Test"
  # EC2 に SSH 接続・デプロイを実行
  deploy:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      # CircleCI に登録した秘密鍵を呼び出す
      - add_ssh_keys:
          fingerprints:
            - "84:6f:f7:ba:08:c2:96:c6:88:9a:25:af:d1:d0:ef:bf"
      # CircleCI に登録した環境変数を使って SSH
      - run: ssh ${USER_NAME}@${HOST_NAME} 'cd /var/www/aws-laravel/ && git pull'

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            # build ジョブに依存してるので、先に build ジョブを実行しろ！
            - build
          # master ブランチに push された場合のみ deploy
          filters:
            branches:
              only: master
